supabaseUrl: "postgresql://postgres:postgres@localhost:5432/postgres"
supabaseRealtimeUrl: "wss://localhost:5432/realtime/v1/websocket"
supabaseAnonKey: "replace-with-actual-anon-key"
pathToDockerCompose: "./config/docker-compose.yaml"
frontendServiceName: "frontend"
backendServiceName: "backend"
statsServiceName: "stats"
table: "silos"
chainId: "replace-with-actual-chain-id"
